"""empty message

Revision ID: 34fd64de2201
Revises: 97a04b622596
Create Date: 2020-07-02 21:16:36.263829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34fd64de2201'
down_revision = '97a04b622596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SemCals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('showname_model_str', sa.String(length=64), nullable=True),
    sa.Column('showname_model_en', sa.String(length=128), nullable=True),
    sa.Column('autor', sa.String(length=64), nullable=True),
    sa.Column('references', sa.String(length=256), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('institute', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=64), nullable=True),
    sa.Column('accuracy_rate', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('openday', sa.DateTime(), nullable=True),
    sa.Column('backgroundpicture', sa.String(length=256), nullable=True),
    sa.Column('flag', sa.Boolean(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SemCals')
    # ### end Alembic commands ###
